---
- name: Configure all servers
  hosts: all
  become: yes
  vars:
    db_name: webinar_db
    db_user: adminuser
  roles:
    - common

- name: Configure Database
  hosts: database
  become: yes
  roles:
    - database

- name: Configure MinIO
  hosts: minio
  become: yes
  vars:
    minio_root_user: minioadmin
    minio_root_password: minioadmin
  roles:
    - minio

- name: Configure Backend
  hosts: backend
  become: yes
  roles:
    - backend

- name: Configure Proxy
  hosts: proxy
  become: yes
  roles:
    - proxy